image: python:buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - ./recept.py generate
  except:
  - master

pages:
  script:
  - ./recept.py generate
  artifacts:
    paths:
    - public
  only:
  - master
