image: python:buster

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - pip install pystache
  - ./recept.py generate --input content
  except:
  - master

pages:
  script:
  - pip install pystache
  - ./recept.py generate --input content
  artifacts:
    paths:
    - generated
  only:
  - master
