baseURL = "https://madeso.gitlab.io/recept/"
languageCode = "en-us"
title = "Gustavs recept"

theme = "kiss"
copyright = "Samlat av Gustav"
disqusShortname = ""
googleAnalytics = ""
# Number of posts per page
Paginate = 5
enableRobotsTXT = true

[taxonomies]
tag ="tags"
category ="category"
